#!/bin/bash
# Deployment script for social-agent-hackathon

echo "🚀 Deploying Twitter Integration to Railway"
echo ""
echo "Current status:"
git status --short

echo ""
echo "Recent commits (ready to push):"
git log --oneline -5

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  Manual push required"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The code is committed locally but needs to be pushed to GitHub."
echo ""
echo "OPTIONS:"
echo ""
echo "1. Push from your local machine:"
echo "   cd /path/to/social-agent-hackathon"
echo "   git pull origin main"
echo "   git push origin main"
echo ""
echo "2. Or set up GitHub Personal Access Token here:"
echo "   a. Go to: https://github.com/settings/tokens"
echo "   b. Generate new token (classic)"
echo "   c. Select 'repo' scope"
echo "   d. Copy the token"
echo "   e. Run: git remote set-url origin https://TOKEN@github.com/srpenmats/social-agent-hackathon.git"
echo "   f. Run: git push origin main"
echo ""
echo "3. Or create a pull request:"
echo "   git format-patch HEAD~1"
echo "   # Upload the patch file to GitHub"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After push completes:"
echo "1. Railway will auto-deploy in ~2 minutes"
echo "2. Set TWITTER_BEARER_TOKEN on Railway:"
echo "   railway variables set TWITTER_BEARER_TOKEN=\"your_token\""
echo "3. Test: curl https://your-app.railway.app/api/v1/health"
echo ""
